### ISSUE TITLE
Unexpected splitting of expression enclosed with ${} in multi line string

### ISSUE THREAD

**Issue by fadenb** [serokell/nixfmt#4]
Hey :)

I used `nixfmt` on some real world code and mostly like what it does. One thing I noticed is the following:

```
[...]
  services.udev.extraRules = ''
    KERNEL=="zd*" SUBSYSTEM=="block" ACTION=="add|change" PROGRAM="${pkgs.zfs}/lib/udev/zvol_id /dev/%k" GROUP="zfs" MODE="0770"
  '';
[...]
```

was changed to

```
[...]
  services.udev.extraRules = ''
    KERNEL=="zd*" SUBSYSTEM=="block" ACTION=="add|change" PROGRAM="${
      pkgs.zfs
    }/lib/udev/zvol_id /dev/%k" GROUP="zfs" MODE="0770"
  '';
[...]
```

The generated rule file still has the same content (👍) but I believe the original style is easier to read.

**Comment by Lucus16** [comment]
This is a bit of a tricky choice. The advantage of splitting it this way is that we can stay within the target width much more often. I believe when you get used to it, this is easier to read than long lines that get wrapped at the terminal width, rather than any semantic position.

I'd like to hear the opinions of more people on this.

**Comment by kirelagin** [comment]
I think it is best to follow what the author of the code did. That is, if it is just `${...}`, then leave it as is, even if it means wrapping. However, if the opening `${` and the closing `}` are on different lines, then hit the expression in braces with the full power of our pretty-printing magic.

**Comment by Lucus16** [comment]
This is not compatible with a fully opinionated formatter. All original
formatting except for newlines and comments is thrown away during parsing,
to enforce a consistent style.

**Comment by kirelagin** [comment]
I would still argue that this presence or lack of a newline between the braces matters just as much (actually even more) than those newlines that we already preserve. And if there was no newline, then, ok, we can reformat the code, but we should not introduce line breaks.

I guess my argument for not introducing line breaks boils down to this:

* If we hit the line limit, it is very likely not because of the interpolated code, but rather of the structure of the text we are generating itself (i.e. a long udev rule line, as in the example) – the line length issue should be fixed in the target template, not in Nix.
* Interpolating complex expressions seems to be a terrible idea in any case. The correct way to fix a too long interpolate expression is to extract it into a `let`, not split it across lines. I don’t have any statistics, but I would _hope_ that the vast majority of interpolations interpolate a single variable, or a single function call, or something else really-really simple and short, so the current behaviour will actually do more damage than good by smudging trivial things like `pkgs.foo` or `cfg.hi or "boom"` across multiple lines.
* > when you get used to it, this is easier to read

  Sorry, I don’t buy it :). I’ll be honest, it looks quite bad and I can’t imagine me getting used to this.

**Comment by Lucus16** [comment]
I think in that case, it's better to keep identifiers and selections on a
single line and to split other expressions. I expect this is a good
approximation of the uses in nixpkgs.

**Comment by Lucus16** [comment]
I pushed some code recently which avoids splitting on identifiers and selections, like `foo.bar`. You can check if this gives acceptable results at https://nixfmt.serokell.io/ or by pulling from master.

**Comment by yorickvP** [comment]
Closing for now, as the initial case is fixed. If more of these show up, please complain :)
