### ISSUE TITLE
Escape Characters

### ISSUE THREAD

**Issue by 0x4A6F** [serokell/nixfmt#81]
### Description

ofBorg failure with `undefined variable ‘PYTHON_EXECUTABLE’ at ./pkgs/development/compilers/nextpnr/default.nix:57:22` after `nixfmt` run.

### Small example input

```nix
  patchPhase = with builtins; ''
    # use PyPy for icestorm if enabled
    substituteInPlace ./ice40/CMakeLists.txt \
      --replace ''\'''${PYTHON_EXECUTABLE}' '${icestorm.pythonInterp}'
  '';
```

### Expected output

```nix
  patchPhase = with builtins; ''
    # use PyPy for icestorm if enabled
    substituteInPlace ./ice40/CMakeLists.txt \
      --replace ''\'''${PYTHON_EXECUTABLE}' '${icestorm.pythonInterp}'
  '';
```

### Actual output

```nix
  patchPhase = with builtins; ''
    # use PyPy for icestorm if enabled
    substituteInPlace ./ice40/CMakeLists.txt \
      --replace '''${PYTHON_EXECUTABLE}' '${icestorm.pythonInterp}'
  '';
```

**Comment by Heimdell** [comment]
The bug is in parser. It ignores the `''` "escape" sequence and just splices `\n` out of `''\n` into the parsed string.

**Comment by Lucus16** [comment]
The parser is correct:
```
*Nixfmt Nixfmt.Parser Text.Megaparsec> parse file "stdin" "'' ''\\'''${foo}' ''"
Right (File (Ann SOF Nothing []) (Term (String (Ann [[TextPart "'${foo}' "]] Nothing []))))
```
Note that the double backslash is for haskell to generate a single backslash.
The problem is likely that the pretty printer doesn't know about this edge case.

**Comment by Lucus16** [comment]
Right now, reinserting escapes for characters that would otherwise compose to mean other escape sequences is handled by this fairly simple piece of code: https://github.com/serokell/nixfmt/blob/5e004dddb8e5cf6d3c974643bc0b1c3d696a4631/src/Nixfmt/Pretty.hs#L388-L391
That should probably be replaced with something that can handle any sequence of single quotes followed by up to two other characters. It may also need to be aware of whether it is followed by the end of the indented string or an interpolation. It's not an easy algorithm to figure out.
